pub mod agents;
pub mod notifier;
pub mod command_resolver;
pub mod config;
pub mod context;
pub mod gateway;
pub mod github_ops;
pub mod interface;
pub mod mcp;
pub mod memory;
pub mod orchestrator;
pub mod router;
pub mod runtime;
pub mod scheduler;
pub mod session_workspace;
pub mod terminal;
pub mod types;
pub mod webhook;

pub type AppResult<T> = anyhow::Result<T>;
